name: Deploy Preview Environment

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'

env:
  NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
  NEON_PROJECT_ID: ${{ secrets.NEON_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  deploy-preview:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v8

      - name: Create Neon Branch
        id: create-neon-branch
        uses: neondatabase/create-branch-action@v4
        with:
          project_id: ${{ env.NEON_PROJECT_ID }}
          api_key: ${{ env.NEON_API_KEY }}
          database: employees
          branch_name: preview/pr-${{ github.event.number }}
          parent: anonymized-main

      - name: Prepare .env file to be used by vercel build
        run: |
          touch .env

          echo DATABASE_URL=${{ steps.create-neon-branch.outputs.db_url_with_pooler }}?sslmode=require >> .env

      - name: Install Vercel CLI
        run: npm install --global vercel@33

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ env.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ env.VERCEL_TOKEN }}

      - name: Deploy Preview to Vercel
        id: deploy
        run: echo preview_url=$(vercel deploy --prebuilt --token=${{ env.VERCEL_TOKEN }}) >> $GITHUB_OUTPUT

      - name: Set DATABASE_URL on Vercel Preview Deployment
        run: echo "${{ steps.create-neon-branch.outputs.db_url_with_pooler }}?sslmode=require" | vercel env add DATABASE_URL preview ${{ steps.branch-name.outputs.current_branch }} --token=${{ env.VERCEL_TOKEN }}

      - name: Comment on Pull Request
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Vercel Preview URL :rocket: : ${{ steps.deploy.outputs.preview_url }}
            Neon Branch :elephant: : https://console.neon.tech/app/projects/${{ env.NEON_PROJECT_ID }}/branches/${{ steps.create-neon-branch.outputs.branch_id }}
          comment_tag: preview-url
